version: '3'
services:

  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      # persist data even if container shuts down
      - db:/var/lib/postgresql/data/
    networks:
      - shieldwall

#  shieldwall_api:
#    container_name: shieldwall_api
#    image: shieldwall_api:latest
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - database
#    ports:
#      - 8666:8666
#    volumes:
#      - ./api.yaml:/etc/shieldwall/config.yaml
#    restart: unless-stopped
#    networks:
#      - shieldwall

volumes:
  db:
  data:

networks:
  shieldwall:
    driver: bridge